<?php

class Token{
    //generate token to avoid Cross Site Request Forgery Attacks
    public static function generate(){
        return Session::put(Config::get('session/token_name'), md5(uniqid()));
    }
    
    //check if token generated by the form is equal to the one that exists in 
    //session token
    public static function check($token){
        $tokenName = Config::get('session/token_name');
        
        if (Session::exists($tokenName) && $token === Session::get($tokenName)){
            Session::delete($tokenName);
            return TRUE;
        }
        
        return FALSE;
    }
}

